# ============================================================================
# Wemos D1 Mini - Gas Meter with Reed Contact
# ============================================================================
# Configuration for reading a gas meter using a reed contact sensor
# Reed contact connected to D2 (GPIO4) and GND

# Substitutions: Variables that can be reused throughout this configuration
substitutions:
  # The internal name used by ESPHome (use lowercase, no spaces, hyphens OK)
  devicename: "gas-meter"

  # The friendly name shown in Home Assistant (can have spaces and capitals)
  friendly_name: "Gas Meter"

  # Description of what this device does
  device_comment: "Gas Meter Reader with Reed Contact"

  # How many pulses equal 1 cubic meter of gas (adjust for your meter)
  # Common values: 1, 10, 100, 1000
  # Check your gas meter's specification
  # This meter: 0.01m³ per pulse = 100 pulses per m³
  pulses_per_cubic_meter: "100"

  # Initial meter reading offset in m³
  # Set this to your current gas meter reading (e.g., 1234 if your meter shows 1234m³)
  # This value can be adjusted anytime via Home Assistant
  initial_meter_offset: "0"

# ============================================================================
# Core ESPHome Configuration
# ============================================================================
esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  comment: ${device_comment}
  name_add_mac_suffix: false
  # Restore pulse count on boot
  on_boot:
    priority: -100
    then:
      - pulse_meter.set_total_pulses:
          id: gas_pulse_meter
          value: !lambda 'return id(total_pulses_global);'

# ============================================================================
# ESP8266 Hardware Configuration
# ============================================================================
esp8266:
  board: d1_mini

# ============================================================================
# Logger - Serial Output for Debugging
# ============================================================================
logger:
  # ESP8266 uses traditional UART, standard baud rate
  baud_rate: 115200
  level: DEBUG

# ============================================================================
# Home Assistant API - Communication with Home Assistant
# ============================================================================
api:
  encryption:
    key: !secret encryption_key

# ============================================================================
# MQTT - Send data to MQTT broker
# ============================================================================
mqtt:
  broker: mqtt.home
  # Disable Home Assistant Discovery via MQTT to avoid conflicts with API
  discovery: false
  # Optional: Set a topic prefix for all MQTT messages
  topic_prefix: esphome/gas-meter

# ============================================================================
# OTA Updates - Update Firmware Over WiFi
# ============================================================================
ota:
  platform: esphome
  password: !secret ota_password

# ============================================================================
# Preferences - Save data to flash memory
# ============================================================================
# This ensures sensor values are saved and restored after reboot
preferences:
  flash_write_interval: 1min

# ============================================================================
# Globals - Persistent variables
# ============================================================================
# This global variable stores the total pulse count and survives reboots
globals:
  - id: total_pulses_global
    type: int
    restore_value: true
    initial_value: '0'

  # Meter reading offset in m³ (for starting at existing meter value)
  - id: meter_offset
    type: float
    restore_value: true
    initial_value: '${initial_meter_offset}'

# ============================================================================
# WiFi Configuration
# ============================================================================
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Fallback Access Point
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret ap_password
    ap_timeout: 15s

# ============================================================================
# Web Server - Control Device from Web Browser
# ============================================================================
web_server:
  port: 80

# ============================================================================
# Time - Synchronize Clock with Home Assistant
# ============================================================================
time:
  - platform: homeassistant
    id: homeassistant_time

# ============================================================================
# Captive Portal - Easy WiFi Setup
# ============================================================================
captive_portal:

# ============================================================================
# Internal LED - Status Indicator
# ============================================================================
# Wemos D1 Mini has internal blue LED on GPIO2 (D4)
output:
  - platform: gpio
    pin: GPIO2
    inverted: true
    id: internal_led

light:
  - platform: binary
    output: internal_led
    id: led
    name: "${friendly_name} LED"
    restore_mode: RESTORE_DEFAULT_OFF

# ============================================================================
# Binary Sensors - On/Off Sensors
# ============================================================================
binary_sensor:
  # Status Sensor - Shows if device is online or offline
  - platform: status
    name: "${friendly_name} Status"

# ============================================================================
# Sensors - Numeric Sensors
# ============================================================================
sensor:
  # Pulse Meter - Counts pulses and calculates flow rate
  - platform: pulse_meter
    id: gas_pulse_meter
    name: "${friendly_name} Flow Rate"
    # Connect to the reed contact pin D2 (GPIO4)
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    # Unit of measurement
    unit_of_measurement: "m³/h"
    accuracy_decimals: 2
    icon: "mdi:fire"
    # Timeout: if no pulse for 2 minutes, assume flow = 0
    timeout: 2min
    # Internal filter mode: PULSE counts complete pulse cycles (close + open = 1 pulse)
    # EDGE would count close AND open as 2 separate pulses (incorrect)
    internal_filter_mode: PULSE
    # Internal filter: Ignore pulses closer than 100ms (debouncing)
    internal_filter: 100ms
    # Filters
    filters:
      # Each pulse represents 1/pulses_per_cubic_meter cubic meters
      # Multiply by 60 to convert from m³/min to m³/h
      - multiply: !lambda "return 60.0 / ${pulses_per_cubic_meter};"
    # Visual feedback: LED leuchtet für 3 Sekunden
    on_raw_value:
      then:
        # Update global pulse counter for persistence
        - lambda: |-
            id(total_pulses_global) += 1;
        # LED feedback - simple on/off for internal LED
        - light.turn_on: led
        # LED bleibt für 3 Sekunden an
        - delay: 3s
        - light.turn_off: led
    # Total counter - tracks total gas consumption
    total:
      name: "${friendly_name} Total"
      id: pulse_meter_total
      unit_of_measurement: "m³"
      accuracy_decimals: 2
      icon: "mdi:counter"
      # State class tells Home Assistant this is a cumulative value
      state_class: total_increasing
      # Device class for gas consumption
      device_class: gas
      # Convert pulses to cubic meters
      filters:
        - multiply: !lambda "return 1.0 / ${pulses_per_cubic_meter};"

  # Total Pulses - Raw pulse count (without conversion to m³)
  - platform: copy
    source_id: pulse_meter_total
    name: "${friendly_name} Total Pulses"
    unit_of_measurement: "pulses"
    accuracy_decimals: 0
    icon: "mdi:counter"
    filters:
      # Multiply back to get raw pulses
      - multiply: ${pulses_per_cubic_meter}

  # WiFi Signal Strength
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  # Uptime Sensor
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s

  # Actual Meter Reading - Combines measured consumption with offset
  - platform: template
    name: "${friendly_name} Meter Reading"
    id: actual_meter_reading
    unit_of_measurement: "m³"
    accuracy_decimals: 2
    icon: "mdi:counter"
    state_class: total_increasing
    device_class: gas
    # Calculate: offset + measured consumption
    lambda: |-
      return id(meter_offset) + id(pulse_meter_total).state;
    update_interval: 10s

# ============================================================================
# Button - Executable actions
# ============================================================================
button:
  # Reset pulse counter - Sets measured consumption back to zero
  - platform: template
    name: "${friendly_name} Reset Pulses"
    icon: "mdi:restart"
    on_press:
      - lambda: |-
          id(total_pulses_global) = 0;
          id(gas_pulse_meter).set_total_pulses(0);

# ============================================================================
# Number - Adjustable numeric values
# ============================================================================
number:
  # Meter Offset - Set your actual meter reading here
  - platform: template
    name: "${friendly_name} Meter Offset"
    id: meter_offset_number
    min_value: 0
    max_value: 999999
    step: 0.01
    unit_of_measurement: "m³"
    icon: "mdi:counter"
    # Read current value from global variable
    lambda: |-
      return id(meter_offset);
    # When user changes the value, update global variable
    set_action:
      - lambda: |-
          id(meter_offset) = x;